[package]
name = "learning-rust"
version = "0.0.1"
edition = "2024"

[[bin]]
name = "parity_test"
path = "bin/parity_test.rs"

[[bin]]
name = "bits_test"
path = "bin/bits_test.rs"

[[bin]]
name = "lrc_test"
path = "bin/lrc_test.rs"

[[bin]]
name = "crc32_test"
path = "bin/crc32_test.rs"

[[bin]]
name = "encode"
path = "bin/encode.rs"

[[bin]]
name = "decode"
path = "bin/decode.rs"

[[bin]]
name = "lz77"
path = "bin/lz77.rs"

[[bin]]
name = "gzip"
path = "bin/gzip.rs"

[dependencies]
